name: Build

on:
  push:
    branches:
      - main
      - master
      - "releases/**"
      - "feature/**"
      - "bugfix/**"
  pull_request:
    branches:
      - main
      - master
      - "releases/**"
      - "feature/**"
      - "bugfix/**"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        uses: docker://golang:1.18.0-bullseye
        with:
          args: make lint build
            
          