name: Build

on:
  push:
    branches:
      - main
      - master
      - "releases/**"
      - "feature/**"
      - "bugfix/**"
  pull_request:
    branches:
      - main
      - master
      - "releases/**"
      - "feature/**"
      - "bugfix/**"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        uses: docker://golang:1.18.0-bullseye
        with:
          args: make lint buildbin
      - uses: montudor/action-zip@v1
        with:
          args: zip bin/translator-proxy-win.zip bin/translator-proxy.exe
      - uses: montudor/action-zip@v1
        with:
          args: zip bin/translator-proxy-linux.zip bin/translator-proxy-linux
      - uses: montudor/action-zip@v1
        with:
          args: zip bin/translator-proxy-mac.zip bin/translator-proxy-mac          
            
          