name: Handle Release
on:
  release:
    types: [created,edited]
jobs:
  generate:
    name: create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build artifacts
        uses: docker://golang:1.18.0-bullseye
        with:
          args: make buildbin
      - uses: montudor/action-zip@v1
        with:
          args: zip -j bin/translator-proxy-win.zip bin/translator-proxy.exe
      - uses: montudor/action-zip@v1
        with:
          args: zip -j bin/translator-proxy-linux.zip bin/translator-proxy-linux
      - uses: montudor/action-zip@v1
        with:
          args: zip -j bin/translator-proxy-mac.zip bin/translator-proxy-mac
      - name: upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'bin/*.zip'